### ISSUE TITLE
Please add compatibility for solarfocus firmware 25.05 - (After HA update to 20250806.0 the data connection doesn't work anymore)

### ISSUE THREAD

**Issue by mindestens** [LavermanJJ/home-assistant-solarfocus#147]
After the update to HA 20250806.0 all values are gone

**Desktop**
 - Home assistant version: 20250806.0
 - Solarfocus custom component version: 5.0.0-rc3
 - Solarfocus firmware version: 25.050

**Screenshots**
<img width="322" height="561" alt="Image" src="https://github.com/user-attachments/assets/3519fb1f-dbb5-4d2e-8aac-89646e68bbc8" />

**Additional context**
- HA restarted and reload of the device does't fix the issue
- Debug log enabled:

```
Logger: root
Quelle: /usr/local/lib/python3.13/site-packages/pysolarfocus/components/base/component.py:161
Erstmals aufgetreten: 18:00:16 (800 Vorkommnisse)
Zuletzt protokolliert: 18:13:32

Failed to read holding registers of HeatingCircuit
Failed to read holding registers of Buffer
Failed to read holding registers of Boiler
Failed to read holding registers of HeatPump
Failed to read holding registers of Photovoltaic
```

```
Logger: root
Quelle: /usr/local/lib/python3.13/site-packages/pysolarfocus/modbus_wrapper.py:71
Erstmals aufgetreten: 18:00:16 (800 Vorkommnisse)
Zuletzt protokolliert: 18:13:32

Exception while reading holding registers for address: '32600'!
Exception while reading holding registers for address: '34000'!
Exception while reading holding registers for address: '32000'!
Exception while reading holding registers for address: '33404'!
Exception while reading holding registers for address: '33407'!
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pysolarfocus/modbus_wrapper.py", line 63, in read_holding_registers
    result = self.client.read_holding_registers(address=register_slice.absolute_address, count=register_slice.count, **self.__slave_args)
TypeError: ModbusClientMixin.read_holding_registers() got an unexpected keyword argument 'slave'
```

```
Logger: root
Quelle: /usr/local/lib/python3.13/site-packages/pysolarfocus/modbus_wrapper.py:52
Erstmals aufgetreten: 18:00:16 (800 Vorkommnisse)
Zuletzt protokolliert: 18:13:32

Exception while reading input registers for address: '1100'!
Exception while reading input registers for address: '1900'!
Exception while reading input registers for address: '500'!
Exception while reading input registers for address: '2300'!
Exception while reading input registers for address: '2500'!
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pysolarfocus/modbus_wrapper.py", line 44, in read_input_registers
    result = self.client.read_input_registers(address=register_slice.absolute_address, count=register_slice.count, **self.__slave_args)
TypeError: ModbusClientMixin.read_input_registers() got an unexpected keyword argument 'slave'
```

Thanks!

**Comment by mindestens** [comment]
**Update** 

After restoring HA 20250702.3 the issue is still present. I can't confirm, but it feels like it is related to the Solarfocus firmware version **25.050** 

Still no clue why it worked before properly.

Please let me know if you need additional details!

Thank you!!

**Comment by LavermanJJ** [comment]
Thanks for the info - I've also experienced some weird behavior when testing in my dev setup - maybe it is related to the latest changes from solarfocus 25.x

**Comment by LavermanJJ** [comment]
I just updated to 2025.8.0 HA core. For me it worked like a charm.

May restarting your solarfocus eco-manager might help?

**Comment by mindestens** [comment]
OK, then it seems related to the Solardocus 25.050 firmware. (I still have no clue why it worked flawlessly before the update, but never mind…)

Can I provide additional details/information to help add compatibility with this firmware version?

Thanks!

**Comment by LavermanJJ** [comment]
You could ask solarfocus oid they changed something in between these versions related to the modbus.

However, as I also experienced similar behavior during development of the API client when trying to connect to my eco-manager - it might not be related to the 25.050 version.

Maybe I find some time to check again with my test setup and reproduce it

**Comment by LavermanJJ** [comment]
Indeed I missed it. I'll check.

**Comment by Vaszago** [comment]
> Which solarfocus firmware are you on? I had no clue that an auto update is enabled, as I was last month on 25.030 - and now it shows 25.0**5**0

Where did you set the automatic update? I can't find anything about it in my settings. Where exactly would that be?

I also contacted solarfocus in the spring because they had a firmware error in the heat pump's cooling mode. I also received the 25,030 at the time, and a lot of the heat pump's values were missing. But they then sent me a version with the old Modbus configuration, and with that, all the sensors worked again.

The technician said they've made the Modbus protocol more efficient.

Previously, the values were always transmitted individually, and now they are transmitted in blocks to reduce network traffic.

@LavermanJJ 
I think that might be the reason for the missing sensor data via Modbus.

**Comment by mindestens** [comment]
@Vaszago Thank you for the valuable information!

To be honest I've no other explanation as an auto update feature. 
Last month, I had the yearly service done by Solarfocus, during which the firmware was updated to 25.020. (Not 25.030 it was a typo! - as I reported another [issue](https://github.com/LavermanJJ/home-assistant-solarfocus/issues/146), as one sensor was missing after the update.)
Since then, I haven’t touched the system. But after I've updated Home Assistant and the integration was broken, I started the investigation and noticed that the Solarfocus firmware is now 25.050 🤷‍♀️

I'll reach out to solarfocus and report back as soon I've more information.

**Comment by Vaszago** [comment]
That surprises me. The Solarfocus technician told me that the 7" touch panel doesn't have enough RAM, which prevents online updates. The issue has been resolved except for newer devices. My system was installed three years ago.

Perhaps Solarfocus can create a customized version for you with the old Modbus configuration. But it would be best if the developer changed the query.

**Comment by LavermanJJ** [comment]
Thanks for reporting - I'm using HAOS

**Comment by nils512** [comment]
I see the same issue.

Solarfocus was updated recently to V25.050 - but was running fine since then.
After Updating Home-Assistant from 2025.8 to 2025.8.1, i'm facing the same issue.
A restart of the TCP interface on the Solarfocus and Home-Assistant could not solve the issue.
I'm running Home-Assistant in Docker.

**Comment by LavermanJJ** [comment]
@RobertoCravallo thanks for reporting. What HA installation type are you using? (HAOS, Docker, Supervised,...)

**Comment by lu-zero** [comment]
By looking at https://pypi.org/project/pymodbus/#history my guess is that it might break semver.

**Comment by lu-zero** [comment]
https://github.com/LavermanJJ/pysolarfocus/pull/48 fixes the problem,  #148 and #149 are dupes.

**Comment by mindestens** [comment]
@lu-zero You nailed it!
Thank you very much!! I can confirm its working with your changes! 👍

**Comment by LavermanJJ** [comment]
Are you referring to 

`got an unexpected keyword argument 'slave' `?

If so, then yes

**Comment by Vaszago** [comment]
I'm only asking because SolarFocus sent me version 25.03, and the Modbus query didn't work with that version. It only worked again when SolarFocus sent me a modified version with the old Modbus configuration. I sent you the file, but I can't say if that was the problem.

**Comment by nils512** [comment]
Nice thank you!
It is working again with 5.0.0-rc4.

But all sensors related to the solar-system are not updated anymore.
I changed to "25.030" in the integration, but still i get the same errors:

```
    Error adding entity sensor.solarfocus_solar_collector_supply_temperature for domain sensor with platform solarfocus
    Error adding entity sensor.solarfocus_solar_current_power for domain sensor with platform solarfocus
    Error adding entity sensor.solarfocus_solar_current_yield_heat_meter for domain sensor with platform solarfocus
    Error adding entity sensor.solarfocus_solar_buffer_sensor_1 for domain sensor with platform solarfocus
    Error adding entity sensor.solarfocus_solar_state for domain sensor with platform solarfocus

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 676, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1382, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1026, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1151, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1088, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1032, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 548, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarfocus/sensor.py", line 214, in native_value
    return self._get_native_value(sensor)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/config/custom_components/solarfocus/entity.py", line 195, in _get_native_value
    native_value = getattr(component, item).scaled_value
                   ~~~~~~~^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'collector_temperature_1'
```

**Comment by RobertoCravallo** [comment]
I have only this.....

![Image](https://github.com/user-attachments/assets/ded22067-534e-437d-90ab-c2e6540c2880)

**Comment by LavermanJJ** [comment]
Can you please create separate issues for them? Thanks

**Comment by jahrer** [comment]
Thanks a lot!!!
