### ISSUE TITLE
Update to HA 2025.08.X - solarfocus integration does not work anymore

### ISSUE THREAD

**Issue by shredman01** [LavermanJJ/home-assistant-solarfocus#149]
The solarfocus integration does not transmit any values to HA since the update of homeassistant core to version 202508.x . Changing to different api versions doesn't help and I get alot of errormessages in the logs

Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:350
Erstmals aufgetreten: 11:24:48 (1 Vorkommnis)
Zuletzt protokolliert: 11:24:48
Detected that custom integration 'solarfocus' sets option flow config_entry explicitly, which is deprecated at custom_components/solarfocus/config_flow.py, line 285: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/lavermanjj/home-assistant-solarfocus/issues 

Logger: root
Quelle: /usr/local/lib/python3.13/site-packages/pysolarfocus/modbus_wrapper.py:52
Erstmals aufgetreten: 09:16:46 (3914 Vorkommnisse)
Zuletzt protokolliert: 11:25:44

Exception while reading input registers for address: '1100'!
Exception while reading input registers for address: '1900'!
Exception while reading input registers for address: '500'!
Exception while reading input registers for address: '2400'!
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pysolarfocus/modbus_wrapper.py", line 44, in read_input_registers
    result = self.client.read_input_registers(address=register_slice.absolute_address, count=register_slice.count, **self.__slave_args)
TypeError: ModbusClientMixin.read_input_registers() got an unexpected keyword argument 'slave'

<img width="482" height="637" alt="Image" src="https://github.com/user-attachments/assets/f28271ef-8f97-4ade-83b1-a642a4e81b6c" />

![Image](https://github.com/user-attachments/assets/bedc422d-0e69-463c-aa32-268f8d77b888)

can you help ?

regards,
shredman

**Comment by mindestens** [comment]
Fixed in [5.0.0-rc4](https://github.com/LavermanJJ/home-assistant-solarfocus/releases/tag/5.0.0-rc4) 
More details: https://github.com/LavermanJJ/home-assistant-solarfocus/issues/147#issuecomment-3191090032
